name: pim_4chamados
description: Sistema de Gerenciamento de Chamados de TI
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP e API
  dio: ^5.4.0

  # Gerenciamento de Estado
  provider: ^6.1.1

  # Armazenamento Local
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Upload de Imagens
  image_picker: ^1.0.7

  # UI/UX
  intl: ^0.19.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.3.0
  path_provider: ^2.1.5
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: BrandonGrotesque
      fonts:
        - asset: assets/fonts/HvDTrial_Brandon_Grotesque_regular-BF64a625c9311e1.otf
        - asset: assets/fonts/HvDTrial_Brandon_Grotesque_bold-BF64a625c9151d5.otf
          weight: 700

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
